### ISSUE TITLE
Size of MON-1B bin file

### ISSUE THREAD

**Issue by a-ernest** [tec1group/software-repo#7]
What happened with the MON-1B bin file? It's 64K instead of 2. Assembled it myself (although it says it is ver. 1A!) and it worked out as it should. Hope you are all keeping well.

**Comment by bchiha** [comment]
Good find.  All my copies are also 64k.  I've reduced one to 2k, I'll upload that soon.

**Comment by bchiha** [comment]
Next Pull Request will include a MON-1B bin file that is 2k... I'll close Issue
